src/objects/FeatureToggle__mdt.object
<CustomObject>
    <description>Feature Toggle Definitions</description>
    <fields>
        <fullName>ActivationDateTime__c</fullName>
        <description>The date and time that the feature will activate upon.</description>
        <inlineHelpText>The date and time that the feature will activate upon.</inlineHelpText>
        <label>Activation Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this checkbox is checked the feature will be active.</description>
        <inlineHelpText>When this checkbox is checked the feature will be active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeactivationDateTime__c</fullName>
        <description>The date and time that the feature will deactivate upon.</description>
        <inlineHelpText>The date and time that the feature will deactivate upon.</inlineHelpText>
        <label>Deactivation Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Feature Toggle</label>
    <pluralLabel>Feature Toggles</pluralLabel>
</CustomObject>

src/classes/FeatureToggleTestHelper.cls
/**
 * @description Test Helpers for Togglr's Feature Toggles.
 */
@isTest
public with sharing class FeatureToggleTestHelper {
    public static FeatureToggle__mdt getActiveFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                ActivationDateTime__c,
                Active__c,
                DeactivationDateTime__c,
                DeveloperName,
                Id,
                Label,
                OrgDefinition__r.OrgId__c
        FROM FeatureToggle__mdt
        WHERE Label = 'Togglr Active Test Record'
        LIMIT 1];
        return featureToggleRecord;
    }

    public static FeatureToggle__mdt getActivationFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                ActivationDateTime__c,
                Active__c,
                DeactivationDateTime__c,
                DeveloperName,
                Id,
                Label,
                OrgDefinition__r.OrgId__c
        FROM FeatureToggle__mdt
        WHERE Label = 'Togglr Activation Test Record'
        LIMIT 1];
        return featureToggleRecord;
    }

    public static FeatureToggle__mdt getInactiveFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                ActivationDateTime__c,
                Active__c,
                DeactivationDateTime__c,
                DeveloperName,
                Id,
                Label,
                OrgDefinition__r.OrgId__c
        FROM FeatureToggle__mdt
        WHERE Label = 'Togglr Deactivation Test Record'
        LIMIT 1];
        return featureToggleRecord;
    }

    public static FeatureToggle__mdt getProductionActiveFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                ActivationDateTime__c,
                Active__c,
                DeactivationDateTime__c,
                DeveloperName,
                Id,
                Label,
                OrgDefinition__r.OrgId__c
        FROM FeatureToggle__mdt
        WHERE Label = 'Production Togglr Active Test Record'
        LIMIT 1];
        return featureToggleRecord;
    }

    public static FeatureToggle__mdt getProductionActivationFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                ActivationDateTime__c,
                Active__c,
                DeactivationDateTime__c,
                DeveloperName,
                Id,
                Label,
                OrgDefinition__r.OrgId__c
        FROM FeatureToggle__mdt
        WHERE Label = 'Production Togglr Activation Test Record'
        LIMIT 1];
        return featureToggleRecord;
    }

    public static FeatureToggle__mdt getProductionInactiveFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                ActivationDateTime__c,
                Active__c,
                DeactivationDateTime__c,
                DeveloperName,
                Id,
                Label,
                OrgDefinition__r.OrgId__c
        FROM FeatureToggle__mdt
        WHERE Label = 'Production Togglr Deactivation Test Record'
        LIMIT 1];
        return featureToggleRecord;
    }
}