src/objects/FeatureToggle__mdt.object
<CustomObject>
    <description>Feature Toggle Definitions</description>
    <fields>
        <fullName>ActivationDateTime__c</fullName>
        <description>The date and time that the feature will activate upon.</description>
        <inlineHelpText>The date and time that the feature will activate upon.</inlineHelpText>
        <label>Activation Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this checkbox is checked the feature will be active.</description>
        <inlineHelpText>When this checkbox is checked the feature will be active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeactivationDateTime__c</fullName>
        <description>The date and time that the feature will deactivate upon.</description>
        <inlineHelpText>The date and time that the feature will deactivate upon.</inlineHelpText>
        <label>Deactivation Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Feature Toggle</label>
    <pluralLabel>Feature Toggles</pluralLabel>
</CustomObject>

src/classes/FeatureToggleTest.cls
@isTest
private class FeatureToggleTest {
    private static FeatureToggle__mdt getActiveFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                                                         ActivationDateTime__c,
                                                         Active__c,
                                                         DeactivationDateTime__c,
                                                         DeveloperName,
                                                         Id,
                                                         Label
                                                    FROM FeatureToggle__mdt
                                                   WHERE Label = 'Togglr Active Test Record'
                                                   LIMIT 1];
        return featureToggleRecord;
    }

    private static FeatureToggle__mdt getActivationFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                                                         ActivationDateTime__c,
                                                         Active__c,
                                                         DeactivationDateTime__c,
                                                         DeveloperName,
                                                         Id,
                                                         Label
                                                    FROM FeatureToggle__mdt
                                                   WHERE Label = 'Togglr Activation Test Record'
                                                   LIMIT 1];
        return featureToggleRecord;
    }

    private static FeatureToggle__mdt getDeactiveFeatureToggleTestRecord() {
        FeatureToggle__mdt featureToggleRecord = [SELECT
                                                         ActivationDateTime__c,
                                                         Active__c,
                                                         DeactivationDateTime__c,
                                                         DeveloperName,
                                                         Id,
                                                         Label
                                                    FROM FeatureToggle__mdt
                                                   WHERE Label = 'Togglr Deactivation Test Record'
                                                   LIMIT 1];
        return featureToggleRecord;
    }

    @isTest
    private static void constructor_nullRecord_expectArgumentNullException() {
        try {
            test.startTest();
            new FeatureToggle(null);

            TestHelper.expectedArgumentNullException();
        } catch (Exception e) {
            TestHelper.assertArgumentNullException(e, FeatureToggle.FEATURE_TOGGLE_PARAM);
        } finally {
            test.stopTest();
        }
    }

    @isTest
    private static void constructor_recordProvided_expectRecordStored() {
        FeatureToggle__mdt featureToggleRecord = getActiveFeatureToggleTestRecord();

        if (featureToggleRecord == null) {
            System.assert(true, 'An admin in the containing org has deleted the test records. Assert true and exit.');
            return;
        }

        Test.startTest();
        FeatureToggle featureToggle = new FeatureToggle(featureToggleRecord);
        Test.stopTest();

        System.assertNotEquals(null, featureToggle.record, 'Expected the FeatureToggle to have a record stored.');
        System.assertEquals(featureToggleRecord, featureToggle.record,
                'Expected the stored record to match the given record.');
    }

    @isTest
    private static void label_expectLabelMatchesRecord() {
        FeatureToggle__mdt featureToggleRecord = getActiveFeatureToggleTestRecord();

        if (featureToggleRecord == null) {
            System.assert(true, 'An admin in the containing org has deleted the test records. Assert true and exit.');
            return;
        }

        FeatureToggle featureToggle = new FeatureToggle(featureToggleRecord);

        Test.startTest();
        String featureToggleLabel = featureToggle.Label;
        Test.stopTest();

        System.assertEquals(featureToggleRecord.Label, featureToggleLabel,
                'Expected the feature toggle labels to match.');
    }

    @isTest
    private static void isActive_activeTrue_expectActive() {
        FeatureToggle__mdt featureToggleRecord = getActiveFeatureToggleTestRecord();

        if (featureToggleRecord == null) {
            System.assert(true, 'An admin in the containing org has deleted the test records. Assert true and exit.');
            return;
        }

        FeatureToggle featureToggle = new FeatureToggle(featureToggleRecord);

        Test.startTest();
        Boolean isActive = featureToggle.IsActive;
        Test.stopTest();

        System.assert(isActive, 'Expected the feature toggle to be active.');
    }

    @isTest
    private static void isActive_activationDateExceeded_expectActive() {
        FeatureToggle__mdt featureToggleRecord = getActivationFeatureToggleTestRecord();

        if (featureToggleRecord == null) {
            System.assert(true, 'An admin in the containing org has deleted the test records. Assert true and exit.');
            return;
        }

        FeatureToggle featureToggle = new FeatureToggle(featureToggleRecord);

        Test.startTest();
        Boolean isActive = featureToggle.IsActive;
        Test.stopTest();

        System.assert(isActive, 'Expected the feature toggle to be active.');
    }

    @isTest
    private static void isActive_deactivationDateExceeded_expectInactive() {
        FeatureToggle__mdt featureToggleRecord = getDeactiveFeatureToggleTestRecord();

        if (featureToggleRecord == null) {
            System.assert(true, 'An admin in the containing org has deleted the test records. Assert true and exit.');
            return;
        }

        FeatureToggle featureToggle = new FeatureToggle(featureToggleRecord);

        Test.startTest();
        Boolean isActive = featureToggle.IsActive;
        Test.stopTest();

        System.assert(!isActive, 'Expected the feature toggle to be inactive.');
    }
}